# http://www.appveyor.com/docs/appveyor-yml

install:
  - npm install phantomjs-prebuilt
  - npm install mocha-appveyor-reporter
  - npm install -g bower
  - npm install
  - bower install

cache:
  - '%APPDATA%\npm-cache'
  - '%APPDATA%\Roaming\bower'

test_script:
  - cmd: npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
